# Generated by Django 2.2.4 on 2021-04-29 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab_01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Users',
        ),
    ]
